"""
Problem: 389. Find the Difference
Difficulty: Easy
Pattern: Bit Manipulation / XOR

Description
You are given two strings s and t.

String t is generated by randomly shuffling string s and then adding
one more character at a random position.

Return the letter that was added to t.

Example:
Input:  s = "abcd", t = "abcde"
Output: "e"

Approach (XOR Trick)
1. XOR all characters from both strings (s + t).
2. Since identical characters cancel out (a ^ a = 0),
   only the extra character remains.

Key Properties:
- a ^ a = 0
- a ^ 0 = a

Time Complexity: O(n)
Space Complexity: O(1)
"""

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:

        result = 0

        for char in s + t:
            result ^= ord(char)

        return chr(result)